[package]
name = "tendermint"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
zkm-zkvm = { path = "../../../crates/zkvm/entrypoint" }
tendermint-light-client-verifier = { version = "0.40.3", default-features = false, features = [
  "rust-crypto",
] }
serde_cbor = "0.11.2"
