[package]
name = "plonk-verifier-host"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
zkm-sdk = { workspace = true }

[build-dependencies]
zkm-build = { workspace = true }
